# Generated by Django 3.1.3 on 2020-11-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=100, verbose_name='Nome Area')),
            ],
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=100, verbose_name='Nome universidade')),
                ('sigla', models.CharField(default=None, max_length=10, verbose_name='Sigla universidade')),
            ],
        ),
        migrations.CreateModel(
            name='Canais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=500, verbose_name='url do canal')),
                ('descricao', models.TextField(default=None, max_length=400, verbose_name='descricao')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yt.areas')),
                ('nome_universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yt.universidade')),
            ],
        ),
    ]
