# Generated by Django 2.2.3 on 2020-12-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canais',
            name='id_canal',
            field=models.CharField(default=None, max_length=500, verbose_name='id_canal'),
        ),
    ]
